logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.pay: DEBUG
    com.github.binarywang.wxpay: DEBUG

wechat:
  pay:
    appId: 123
    mchId: 456
    mchKey: 678
    #subAppId:
    #subMchId:
    keyPath: aaa
  miniapp:
    appid: wx0979e5108bb19647
    secret: 8495795411ce539c2d04eb0693fd228c
    token: 111
    aesKey: 111
    msgDataFormat: JSON

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_prize_draw?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5


server:
  port: 80
  tomcat:
    max-threads: 900
    uri-encoding: utf-8


mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*.xml

swagger:
  enabled: true
  title: swagger
  description: skyisbule.github.com
  version: 1.0
  base-package: com.github.skyisbule.wxpay.controller
  base-path: /**
  exclude-path: /error,/ops/**
  apply-default-response-messages: false
  global-response-message:
    get[1]:
      code: 500
      message: server error
      modelRef: error
    post:
      code : 500
      message: server error
      modelRef: error